### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by fisharebest** [rokde/flysystem-local-database-adapter#1]
I haven't installed the code yet, but a quick code review suggests a few problems with wildcards.

1) Create `foo-bar/baz.txt`
2) Create `foo_bar/baz.txt`
3) Delete the folder `foo_bar`

This will execute the SQL `... WHERE location LIKE 'foo_bar%'` which will delete both folders because the underscore is a wildcard.  Perhaps the folder name needs escaping with something like `addcslashes($folder, '_%)`?

1) Create `foo.txt`
2) Create `foo/bar.txt`
3) Delete the folder `foo`

This will execute the SQL `... WHERE location LIKE 'foo%'` which will delete the file as well as the folder.

Perhaps use `$folder . '/%'` instead of `$folder . '%'`?

**Comment by rokde** [comment]
Can you make a pull request for the changes?

**Comment by rokde** [comment]
The commit 8f30367736cec39d1b800811139f28484cab1b35 solves the problems mentioned. Can you re-check your problems?

**Comment by fisharebest** [comment]
> Can you re-check your problems?

Can you create a tag / release?

To use the code now, I must specify `"minimum-stability": "dev"` in `composer.json`, and this breaks other dependencies.

**Comment by rokde** [comment]
Release 0.0.1 created

**Comment by fisharebest** [comment]
Thanks!
